### ISSUE TITLE
Endgame crash

### ISSUE THREAD

**Issue by DeinFreund** [Anarchid/zkgbai#15]
[f=0068025] <SkirmishAI: ZKGBAI  (team 5)>: exception(java.lang.NullPointerException
 	at zkgbai.kgbutil.Pathfinder.findPath(Pathfinder.java:96)
 	at zkgbai.military.fighterhandlers.RetreatHandler.retreatCowards(RetreatHandler.java:117)
 	at zkgbai.military.fighterhandlers.RetreatHandler.update(RetreatHandler.java:76)
 	at zkgbai.military.MilitaryManager.update(MilitaryManager.java:1233)
 	at zkgbai.ZKGraphBasedAI.update(ZKGraphBasedAI.java:250)
 ) java.lang.NullPointerException

**Comment by aeonios** [comment]
This is such a screwy issue that I'm not sure that a direct fix will actually do much, but I committed anyway. It's honestly probably an engine issue, but whatever.
